/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luckysixjava;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author WIN 10
 */
public class PlayingWindow extends javax.swing.JFrame {

    /**
     * Creates new form PlayingWindow
     */
    int[] generatedNumbers = new int[35];
    boolean[] isNumberAlreadyGenerated = new boolean[49];
    String displayGenerated = "";
    
    public PlayingWindow() {
        initComponents();
        
        this.generateNumbers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFirstFiveBallsContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelCoefficient6 = new javax.swing.JLabel();
        jLabelCoefficient7 = new javax.swing.JLabel();
        jLabelCoefficient8 = new javax.swing.JLabel();
        jLabelCoefficient9 = new javax.swing.JLabel();
        jLabelCoefficient10 = new javax.swing.JLabel();
        jLabelCoefficient11 = new javax.swing.JLabel();
        jLabelCoefficient12 = new javax.swing.JLabel();
        jLabelCoefficient13 = new javax.swing.JLabel();
        jLabelCoefficient14 = new javax.swing.JLabel();
        jLabelCoefficient15 = new javax.swing.JLabel();
        jLabelCoefficient16 = new javax.swing.JLabel();
        jLabelCoefficient17 = new javax.swing.JLabel();
        jLabelCoefficient18 = new javax.swing.JLabel();
        jLabelCoefficient19 = new javax.swing.JLabel();
        jLabelCoefficient20 = new javax.swing.JLabel();
        jLabelCoefficient21 = new javax.swing.JLabel();
        jLabelCoefficient22 = new javax.swing.JLabel();
        jLabelCoefficient23 = new javax.swing.JLabel();
        jLabelCoefficient24 = new javax.swing.JLabel();
        jLabelCoefficient25 = new javax.swing.JLabel();
        jLabelCoefficient26 = new javax.swing.JLabel();
        jLabelCoefficient27 = new javax.swing.JLabel();
        jLabelCoefficient28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelCoefficient29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelCoefficient30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelCoefficient31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelCoefficient32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelCoefficient33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabelCoefficient34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabelCoefficient35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFirstFiveBallsContainer.setBackground(LuckySixJava.BACKGROUND_GREEN);
        jPanelFirstFiveBallsContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 2, 51), 5, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFirstFiveBallsContainerLayout = new javax.swing.GroupLayout(jPanelFirstFiveBallsContainer);
        jPanelFirstFiveBallsContainer.setLayout(jPanelFirstFiveBallsContainerLayout);
        jPanelFirstFiveBallsContainerLayout.setHorizontalGroup(
            jPanelFirstFiveBallsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFirstFiveBallsContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelFirstFiveBallsContainerLayout.setVerticalGroup(
            jPanelFirstFiveBallsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFirstFiveBallsContainerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelFirstFiveBallsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFirstFiveBallsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );

        jPanelContainer.setBackground(LuckySixJava.BACKGROUND_GREEN);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient6.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient6.setText("10 000");

        jLabelCoefficient7.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient7.setText("7 500");

        jLabelCoefficient8.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient8.setText("5 000");

        jLabelCoefficient9.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient9.setText("2 500");

        jLabelCoefficient10.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient10.setText("1 000");

        jLabelCoefficient11.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient11.setText("500");

        jLabelCoefficient12.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient12.setText("300");

        jLabelCoefficient13.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient13.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient13.setText("200");

        jLabelCoefficient14.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient14.setText("150");

        jLabelCoefficient15.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient15.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient15.setText("100");

        jLabelCoefficient16.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient16.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient16.setText("90");

        jLabelCoefficient17.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient17.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient17.setText("80");

        jLabelCoefficient18.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient18.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient18.setText("70");

        jLabelCoefficient19.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient19.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient19.setText("60");

        jLabelCoefficient20.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient20.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient20.setText("50");

        jLabelCoefficient21.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient21.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient21.setText("40");

        jLabelCoefficient22.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient22.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient22.setText("30");

        jLabelCoefficient23.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient23.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient23.setText("25");

        jLabelCoefficient24.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient24.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient24.setText("20");

        jLabelCoefficient25.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient25.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient25.setText("15");

        jLabelCoefficient26.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient26.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient26.setText("10");

        jLabelCoefficient27.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient27.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient27.setText("9");

        jLabelCoefficient28.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient28.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient28.setText("8");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient29.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient29.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient29.setText("7");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient30.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient30.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient30.setText("6");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient31.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient31.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient31.setText("5");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient32.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient32.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient32.setText("4");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient33.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient33.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient33.setText("3");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient34.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient34.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient34.setText("2");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resursi/icons/circle.png"))); // NOI18N

        jLabelCoefficient35.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        jLabelCoefficient35.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoefficient35.setText("1");

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient19, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient26, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient28, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCoefficient27, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient35, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient33, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCoefficient34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCoefficient12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelContainerLayout.createSequentialGroup()
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient13))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient14)))
                                        .addGroup(jPanelContainerLayout.createSequentialGroup()
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient18))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient19)))
                                        .addGroup(jPanelContainerLayout.createSequentialGroup()
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient21))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient22)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient27))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient28)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCoefficient23)))))
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCoefficient25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCoefficient26))
                                    .addGap(142, 142, 142)))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient11)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient16)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient20)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient24)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient29)))
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCoefficient15)))))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoefficient35))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jPanelFirstFiveBallsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFirstFiveBallsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCoefficient10;
    private javax.swing.JLabel jLabelCoefficient11;
    private javax.swing.JLabel jLabelCoefficient12;
    private javax.swing.JLabel jLabelCoefficient13;
    private javax.swing.JLabel jLabelCoefficient14;
    private javax.swing.JLabel jLabelCoefficient15;
    private javax.swing.JLabel jLabelCoefficient16;
    private javax.swing.JLabel jLabelCoefficient17;
    private javax.swing.JLabel jLabelCoefficient18;
    private javax.swing.JLabel jLabelCoefficient19;
    private javax.swing.JLabel jLabelCoefficient20;
    private javax.swing.JLabel jLabelCoefficient21;
    private javax.swing.JLabel jLabelCoefficient22;
    private javax.swing.JLabel jLabelCoefficient23;
    private javax.swing.JLabel jLabelCoefficient24;
    private javax.swing.JLabel jLabelCoefficient25;
    private javax.swing.JLabel jLabelCoefficient26;
    private javax.swing.JLabel jLabelCoefficient27;
    private javax.swing.JLabel jLabelCoefficient28;
    private javax.swing.JLabel jLabelCoefficient29;
    private javax.swing.JLabel jLabelCoefficient30;
    private javax.swing.JLabel jLabelCoefficient31;
    private javax.swing.JLabel jLabelCoefficient32;
    private javax.swing.JLabel jLabelCoefficient33;
    private javax.swing.JLabel jLabelCoefficient34;
    private javax.swing.JLabel jLabelCoefficient35;
    private javax.swing.JLabel jLabelCoefficient6;
    private javax.swing.JLabel jLabelCoefficient7;
    private javax.swing.JLabel jLabelCoefficient8;
    private javax.swing.JLabel jLabelCoefficient9;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelFirstFiveBallsContainer;
    // End of variables declaration//GEN-END:variables

    private void generateNumbers() {
        
        //Toolkit t = Toolkit.getDefaultToolkit();

        //Image img = t.getImage("putanja do ikonice coska");

        //setIconImage(img);
        
//        ImageIcon icon = new ImageIcon("src/resursi/icons/10m.png");
//        jLabelTestLine.setIcon(icon);
        
        
        
        
        
        //src/resursi/icons/10m.png
        //src/resursi/icons/10m.png
        
        //C:\Users\WIN 10\Desktop\LuckySixJava\src\resursi\icons\10m.png
        
        
        Random rnd = new Random();
        int min_num = 1;
        int max_num = 48;
        
        for(int i = 0; i < 35;){
            int x = rnd.nextInt(max_num - min_num + 1) + min_num;
            
            if(isNumberAlreadyGenerated[x]){
            }else{
                generatedNumbers[i] = x;
                isNumberAlreadyGenerated[x] = true;
                /*
                displayGenerated = displayGenerated + ", " + Integer.toString(generatedNumbers[i]);
                jLabelTestLine.setText(displayGenerated);
                */
                i++;
            }
        }
        
        for(int i = 0; i < 35; i++){
            System.out.println(i+1 + ".: " + generatedNumbers[i]);
            
        }
        
        /*
        
            ImageIcon icon = new ImageIcon("src/resursi/icons/" + generatedNumbers[i] + "m.png");
            jLabelTestLine.setIcon(icon);
        
        */
        
        
        Timer timer = new Timer(1000, new ActionListener() {
            private int i = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (i < 35) {
                    
                    if(i == 0){
                        displayGenerated = displayGenerated + generatedNumbers[i];
                    }else{
                        displayGenerated = displayGenerated + ", " + generatedNumbers[i];
                    }
                    
                    ImageIcon icon = new ImageIcon("src/resursi/icons/" + generatedNumbers[i] + "m.png");
                    
                    
                    switch(i){
                        case 0:
                            
                            jLabel1.setIcon(icon);
                        break;
                        
                        case 1:
                            
                            jLabel2.setIcon(icon);
                        break;
                        
                        case 2:
                            
                            jLabel3.setIcon(icon);
                        break;
                        
                        case 3:
                            
                            jLabel4.setIcon(icon);
                        break;
                        
                        case 4:
                            jLabel5.setIcon(icon);
                        break;
                        
                        case 5:
                            
                            jLabel6.setIcon(icon);
                        break;
                        
                        case 6:
                            
                            jLabel7.setIcon(icon);
                        break;
                        
                        case 7:
                            
                            jLabel8.setIcon(icon);
                        break;
                        
                        case 8:
                            
                            jLabel9.setIcon(icon);
                        break;
                        
                        case 9:
                            jLabel10.setIcon(icon);
                        break;
                        
                        case 10:
                            jLabel11.setIcon(icon);
                        break;
                        
                        case 11:
                            
                            jLabel12.setIcon(icon);
                        break;
                        
                        case 12:
                            
                            jLabel13.setIcon(icon);
                        break;
                        
                        case 13:
                            jLabel14.setIcon(icon);
                        break;
                        
                        case 14:
                            
                            jLabel15.setIcon(icon);
                        break;
                        
                        case 15:
                            
                            jLabel16.setIcon(icon);
                        break;
                        
                        case 16:
                            
                            jLabel17.setIcon(icon);
                        break;
                        
                        case 17:
                            
                            jLabel18.setIcon(icon);
                        break;
                        
                        case 18:
                            jLabel19.setIcon(icon);
                        break;
                        
                        case 19:
                            
                            jLabel20.setIcon(icon);
                        break;
                        
                        case 20:
                            
                            jLabel21.setIcon(icon);
                        break;
                        
                        case 21:
                            
                            jLabel22.setIcon(icon);
                        break;
                        
                        case 22:
                            
                            jLabel23.setIcon(icon);
                        break;
                        
                        case 23:
                            jLabel24.setIcon(icon);
                        break;
                        
                        case 24:
                            jLabel25.setIcon(icon);
                        break;
                        
                        case 25:
                            
                            jLabel26.setIcon(icon);
                        break;
                        
                        case 26:
                            
                            jLabel27.setIcon(icon);
                        break;
                        
                        case 27:
                            
                            jLabel28.setIcon(icon);
                        break;
                        
                        case 28:
                            
                            jLabel29.setIcon(icon);
                        break;
                        
                        case 29:
                            
                            jLabel30.setIcon(icon);
                        break;
                        
                        case 30:
                            
                            jLabel31.setIcon(icon);
                        break;
                        
                        case 31:
                            jLabel32.setIcon(icon);
                        break;
                        
                        case 32:
                            jLabel33.setIcon(icon);
                        break;
                        
                        case 33:
                            
                            jLabel34.setIcon(icon);
                        break;
                        
                        case 34:
                            
                            jLabel35.setIcon(icon);
                        break;
                    }
                    
                    
                    i++;
                } else {
                    ((Timer) e.getSource()).stop(); // Stop the timer after 35 updates
                }
            }
        });
        
        timer.start();
        
    }
}
